---
# Minimal playbook: create a droplet
# NOTE: Set your DO_API_TOKEN in the environment

- name: Provision DigitalOcean Droplet
  hosts: localhost
  gather_facts: false
  vars:
    do_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    droplet_name: "ansible-demo-droplet"
    region: "nyc3"
    size: "s-1vcpu-1gb"
    image: "ubuntu-22-04-x64"
    ssh_key_ids: []  # <-- Fill with your SSH key IDs from DigitalOcean
  tasks:
    - name: Create droplet
      community.digitalocean.digital_ocean_droplet:
        oauth_token: "{{ do_token }}"
        name: "{{ droplet_name }}"
        region: "{{ region }}"
        size: "{{ size }}"
        image: "{{ image }}"
        ssh_keys: "{{ ssh_key_ids }}"
        wait: yes

    - name: Add new droplet to host group
      add_host:
        name: "{{ do_droplet.data.ip_address }}"
        groups: new_droplets

- name: Configure new droplets
  hosts: new_droplets
  become: true
  gather_facts: true
  tasks:
    - name: Install Node.js, npm, and Git
      apt:
        name:
          - nodejs
          - npm
          - git
        state: present
        update_cache: yes
        owner: "{{ ansible_user }}"
        mode: '0644'
